import { Component, OnInit } from '@angular/core';
import { TriggersService } from "../../../services/triggers.service";
import { HelperService } from "../../../common/helper.service";
@Component({
  selector: 'app-triggers',
  templateUrl: './triggers.component.html',
  styleUrls: ['./triggers.component.scss']
})
export class TriggersComponent implements OnInit {

  constructor(private triggerService: TriggersService, private helperService: HelperService) { }

   userJson = [
    {
      "NewName": "Ada",
      "Mobile": 413262488,
      "Email": "ada.zhu80@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Ada",
      "FamilyUsers": "Justin G,Michael G",
      "CreditBalance": "$104.00",
      "Gender": "Female"
    },
    {
      "NewName": "Alex Ge",
      "Mobile": 430458688,
      "Email": "completege1@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Alex Ge",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male"
    },
    {
      "NewName": "AlexR",
      "Mobile": 431391842,
      "Email": "raffier.alex@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Alex Raffier",
      "FamilyUsers": "",
      "CreditBalance": "$208.00",
      "Gender": "Male"
    },
    {
      "NewName": "80kg Alex Zhang",
      "Mobile": 425432866,
      "Email": "alexlongma@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Alex Zhang",
      "FamilyUsers": "",
      "CreditBalance": "$143.00",
      "Gender": "Male"
    },
    {
      "NewName": "Andi",
      "Mobile": 405828485,
      "Email": "andichow@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Andi",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Male"
    },
    {
      "NewName": "Anna Kan",
      "Mobile": 424074803,
      "Email": "Ranekan@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Anna Kan",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female"
    },
    {
      "NewName": "Apple Yuan",
      "Mobile": 404131309,
      "Email": "appleyuan@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Apple",
      "FamilyUsers": "Yongzhen",
      "CreditBalance": "$221.00",
      "Gender": "Female"
    },
    {
      "NewName": "Audrey Chen",
      "Mobile": 411037608,
      "Email": "audreychenyx@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Audrey",
      "FamilyUsers": "Kate Deng",
      "CreditBalance": "$26.00",
      "Gender": "Female"
    },
    {
      "NewName": "Bella",
      "Mobile": 415087758,
      "Email": "apriloz@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Bella",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Female"
    },
    {
      "NewName": "Jennifer Xu",
      "Mobile": 414360152,
      "Email": "jenniferwen00@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jennifer",
      "FamilyUsers": "Ben",
      "CreditBalance": "$13.00",
      "Gender": "Male"
    },
    {
      "NewName": "Benson",
      "Mobile": 416538984,
      "Email": "asfacas13@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Benson",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Brendan",
      "Mobile": 433034006,
      "Email": "brendanlow@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Brendan",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "Bryan",
      "Mobile": 430858417,
      "Email": "henicoo@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Bryan Wang(双鱼王）",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male"
    },
    {
      "NewName": "Canny",
      "Mobile": 410673878,
      "Email": "cannyclk11@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Canny",
      "FamilyUsers": "Simon,Nick,Luke",
      "CreditBalance": "$0.00",
      "Gender": "Female"
    },
    {
      "NewName": "CC",
      "Mobile": 410988832,
      "Email": "cecilsiu428@yahoo.com.au",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "CC",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Female"
    },
    {
      "NewName": "Charles Wang",
      "Mobile": 413734993,
      "Email": "cwang1110@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Charles",
      "FamilyUsers": "Zoe",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Charles Song",
      "Mobile": 416440603,
      "Email": "13467915@student.uts.edu.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Charles Song",
      "FamilyUsers": "",
      "CreditBalance": "$143.00",
      "Gender": "Male"
    },
    {
      "NewName": "Chins",
      "Mobile": 412965086,
      "Email": "chinmay.rangras@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Chins",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male"
    },
    {
      "NewName": "Chook",
      "Mobile": 402504362,
      "Email": "kmchook@outlook.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Chook",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Christina Lee",
      "Mobile": 415415985,
      "Email": "christina3000@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Christina Lee",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Female"
    },
    {
      "NewName": "David Dong",
      "Mobile": 428184056,
      "Email": "David.Iris1314@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "David Dong",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male"
    },
    {
      "NewName": "David He",
      "Mobile": 435528870,
      "Email": "dzch961@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "David He",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "David Wang",
      "Mobile": 436658500,
      "Email": "jiabowang05@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "David W",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male"
    },
    {
      "NewName": "Edward D",
      "Mobile": 403052102,
      "Email": "drd777@outlook.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Edward",
      "FamilyUsers": "Christopher",
      "CreditBalance": "$39.00",
      "Gender": "Male"
    },
    {
      "NewName": "Elaine Ho",
      "Mobile": 452612565,
      "Email": "oikhei@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Elaine Ho",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female"
    },
    {
      "NewName": "Elly赵欣",
      "Mobile": 408642329,
      "Email": "ecnu_2000@163.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Elly赵欣",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female"
    },
    {
      "NewName": "Ethan Jin",
      "Mobile": 468512080,
      "Email": "yingwu.jin@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Ethan电工",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Feng",
      "Mobile": 401599736,
      "Email": "marco_yufeng@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Feng",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "Francis",
      "Mobile": 434087284,
      "Email": "francishe2007@yahoo.com.au",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Francis",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male"
    },
    {
      "NewName": "Frank",
      "Mobile": 402155868,
      "Email": "frankyangtao@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Frank",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Frank Z",
      "Mobile": 415615698,
      "Email": "changle2012@yahoo.com.au",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Frank Zhang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Gary",
      "Mobile": 478151916,
      "Email": "gychang2000@hotmail.com",
      "Grade": "C",
      "GradePoints": 4.6,
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Gary",
      "FamilyUsers": "EnochC",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Glen",
      "Mobile": 406436861,
      "Email": "wangxiao_ch@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Glen",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male"
    },
    {
      "NewName": "Hannah",
      "Mobile": 403649446,
      "Email": "ka_zling@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Hannah",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Female"
    },
    {
      "NewName": "Henry Su",
      "Mobile": 423523823,
      "Email": "henrysuplus@yahoo.com.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Henry",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male"
    },
    {
      "NewName": "Herbert",
      "Mobile": 420572215,
      "Email": "herbertyuan22@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Herbert",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male"
    },
    {
      "NewName": "Hugh",
      "Mobile": 451668958,
      "Email": "huhe1969@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Hugh",
      "FamilyUsers": "Renee",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Cream",
      "Mobile": 431695247,
      "Email": "happyjane_crying@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Iris",
      "FamilyUsers": "Neil,Sean",
      "CreditBalance": "$104.00",
      "Gender": "Female"
    },
    {
      "NewName": "Jack L",
      "Mobile": 404139888,
      "Email": "nice_jack@live.cn",
      "Grade": "F",
      "GradePoints": 0,
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jack(Helen)",
      "FamilyUsers": "Helen,Elma",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "Jacky Z",
      "Mobile": 410138150,
      "Email": "jacky.zhang.au@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jacky Zhang",
      "FamilyUsers": "Megan,Bei,Evan",
      "CreditBalance": "$260.00",
      "Gender": "Male"
    },
    {
      "NewName": "Jason Chin",
      "Mobile": 405536604,
      "Email": "jasonchchin@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jason Chin",
      "FamilyUsers": "Kate(Jason)",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "Jeff Wang",
      "Mobile": 417009871,
      "Email": "wenoch@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jeff",
      "FamilyUsers": "Maggie,Maggie Yao",
      "CreditBalance": "$104.00",
      "Gender": "Male"
    },
    {
      "NewName": "Jency",
      "Mobile": 438680029,
      "Email": "adepttravels@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jency",
      "FamilyUsers": "Jason",
      "CreditBalance": "$26.00",
      "Gender": "Female"
    },
    {
      "NewName": "JessicaW",
      "Mobile": 452581109,
      "Email": "wang_j1122@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jessica W",
      "FamilyUsers": "Jason Z",
      "CreditBalance": "$39.00",
      "Gender": "Female"
    },
    {
      "NewName": "Jim L",
      "Mobile": 466475033,
      "Email": "topliu88@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Jim L",
      "FamilyUsers": "Shirley Y",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "Jocelyn",
      "Mobile": 433848970,
      "Email": "leunglksm@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Joceyln",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Female"
    },
    {
      "NewName": "Josh Zhang",
      "Mobile": 433330987,
      "Email": "joshzhangjobs@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Josh",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "JZ",
      "Mobile": 409979198,
      "Email": "jackeal_zhuj@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "JZ",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Kai",
      "Mobile": 402822228,
      "Email": "kaisquared90@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Kai",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male"
    },
    {
      "NewName": "Karthik",
      "Mobile": 469241444,
      "Email": "r.karthik@yahoo.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Karthik",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male"
    },
    {
      "NewName": "Kathy",
      "Mobile": 414266070,
      "Email": "Kathy0721@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Kathy",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female"
    },
    {
      "NewName": "KevinW",
      "Mobile": 433499901,
      "Email": "kevin.wangwei@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Kevin Wang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Lance",
      "Mobile": 423432057,
      "Email": "truehoho@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Lance",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Lenise",
      "Mobile": 469915138,
      "Email": "lenise_yeoh@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Lenise",
      "FamilyUsers": "Jet,Say",
      "CreditBalance": "$130.00",
      "Gender": "Female"
    },
    {
      "NewName": "Leon",
      "Mobile": 433671656,
      "Email": "leonlai1997@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Leon",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male"
    },
    {
      "NewName": "Lionel",
      "Mobile": 423080826,
      "Email": "lionelong@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Lionel",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male"
    },
    {
      "NewName": "Long",
      "Mobile": 401021568,
      "Email": "h_lx@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Long",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male"
    },
    {
      "NewName": "Luc",
      "Mobile": 413780136,
      "Email": "bei2004@gmail.com",
      "Grade": "C",
      "GradePoints": 5,
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Luc",
      "FamilyUsers": "Sydney,Kate",
      "CreditBalance": "$130.00",
      "Gender": "Male"
    },
    {
      "NewName": "Magesh",
      "Mobile": 424611007,
      "Email": "rymagesh@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Magesh",
      "FamilyUsers": "",
      "CreditBalance": "$104.00",
      "Gender": "Male"
    },
    {
      "NewName": "Maggie 瀚文",
      "Mobile": 468488368,
      "Email": "mzhangau@outlook.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Maggie瀚文书院",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Female"
    },
    {
      "NewName": "Manny",
      "Mobile": 406726588,
      "Email": "manny.gongz@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Manny",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male"
    },
    {
      "NewName": "Mark Chen",
      "Mobile": 466556068,
      "Email": "mloves.chen@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Mark Chen",
      "FamilyUsers": "",
      "CreditBalance": 0,
      "Gender": "Male"
    },
    {
      "NewName": "Matt",
      "Mobile": 439116666,
      "Email": "mattshi81@hotmail.com",
      "Grade": "C",
      "GradePoints": 6,
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Matt",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male"
    },
    {
      "NewName": "Michael",
      "Mobile": 425033441,
      "Email": "845524343@qq.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Michael",
      "FamilyUsers": "Melody",
      "CreditBalance": "$13.00",
      "Gender": "Male"
    },
    {
      "NewName": "Michael Xu",
      "Mobile": 411652088,
      "Email": "michael202125@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Michael Xu",
      "FamilyUsers": "Sarah",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Michael Zhang",
      "Mobile": 421437705,
      "Email": "mzhang668@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Michael Z",
      "FamilyUsers": "MelodyZ",
      "CreditBalance": "$117.00",
      "Gender": "Male"
    },
    {
      "NewName": "Owen",
      "Mobile": 420518070,
      "Email": "zquake@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Owen",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male"
    },
    {
      "NewName": "Patrick H",
      "Mobile": 432125002,
      "Email": "patrickhu26358787@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Patrick Hu",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Peggy",
      "Mobile": 479159678,
      "Email": "peggy.ling.au@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Peggy",
      "FamilyUsers": "Rylan,Lincoln,Mason",
      "CreditBalance": "$26.00",
      "Gender": "Female"
    },
    {
      "NewName": "Peter wang",
      "Mobile": 433007578,
      "Email": "qiudongw@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Peter Wang",
      "FamilyUsers": "Jensen,Eva Wang",
      "CreditBalance": "$13.00",
      "Gender": "Male"
    },
    {
      "NewName": "Poh",
      "Mobile": 413228977,
      "Email": "bukit_chong@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "POH",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male"
    },
    {
      "NewName": "hipolly",
      "Mobile": 415885188,
      "Email": "topollykwok@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Polly",
      "FamilyUsers": "Andrew",
      "CreditBalance": "$52.00",
      "Gender": "Female"
    },
    {
      "NewName": "Prakash",
      "Mobile": 404371773,
      "Email": "Prakash.varu@yahoo.com.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Prakash",
      "FamilyUsers": "",
      "CreditBalance": "$13.00",
      "Gender": "Male"
    },
    {
      "NewName": "RobinZhang",
      "Mobile": 407803979,
      "Email": "cs.zhanghong@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Robin-Lazycat",
      "FamilyUsers": "Ryan",
      "CreditBalance": "$130.00",
      "Gender": "Male"
    },
    {
      "NewName": "Scott Zhuo",
      "Mobile": 406368287,
      "Email": "scott.z.zhuo@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Scott Zuo",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male"
    },
    {
      "NewName": "Shirley",
      "Mobile": 410638127,
      "Email": "shiroly@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Shirley(Eric)",
      "FamilyUsers": "Angus,Marus,Venus",
      "CreditBalance": "$20.00",
      "Gender": "Female"
    },
    {
      "NewName": "Simon T",
      "Mobile": 421132308,
      "Email": "simonpt2000@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Simon T",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Steven Liu",
      "Mobile": 402505299,
      "Email": "2339297951@qq.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Steven Liu",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male"
    },
    {
      "NewName": "Tammy",
      "Mobile": 431662310,
      "Email": "au.tammy@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Tammy",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Female"
    },
    {
      "NewName": "Thomas",
      "Mobile": 422945805,
      "Email": "thomastsang7388@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Thomas",
      "FamilyUsers": "Iris T",
      "CreditBalance": "$260.00",
      "Gender": "Male"
    },
    {
      "NewName": "Ting CA",
      "Mobile": 415226713,
      "Email": "ququ1102@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Ting",
      "FamilyUsers": "Rain",
      "CreditBalance": "$0.00",
      "Gender": "Female"
    },
    {
      "NewName": "Tom",
      "Mobile": 418215888,
      "Email": "shihuaichen@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Tom",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male"
    },
    {
      "NewName": "Tony C",
      "Mobile": 430511668,
      "Email": "tony.cao77@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Tony C",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "Vincent",
      "Mobile": 427392166,
      "Email": "vshc1@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Vincent",
      "FamilyUsers": "Enoch",
      "CreditBalance": "$39.00",
      "Gender": "Male"
    },
    {
      "NewName": "Visitor",
      "Mobile": 0,
      "Email": "visitor@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Visitor1",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "Wei",
      "Mobile": 449984324,
      "Email": "wei_lu@live.com.au",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Wei",
      "FamilyUsers": "",
      "CreditBalance": 0,
      "Gender": "Male"
    },
    {
      "NewName": "Wing",
      "Mobile": 424125197,
      "Email": "wingyang502@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Wing",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female"
    },
    {
      "NewName": "Xiao",
      "Mobile": 434130413,
      "Email": "mailtohx@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Xiao",
      "FamilyUsers": "Mindy,Qiandai,Villy",
      "CreditBalance": "$65.00",
      "Gender": "Male"
    },
    {
      "NewName": "Yang",
      "Mobile": 424907646,
      "Email": "yyl901015@126.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "Yang",
      "FamilyUsers": "Claire",
      "CreditBalance": "$20.00",
      "Gender": "Male"
    },
    {
      "NewName": "Zaka",
      "Mobile": 433396668,
      "Email": "zaka.lei@gmail.com",
      "Grade": "A",
      "GradePoints": 8,
      "IsCreditUser": "",
      "requireChangePassword": "TRUE",
      "OldName": "Zakka",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male"
    },
    {
      "NewName": "何平He",
      "Mobile": 420779229,
      "Email": "1171750071@qq.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "何平",
      "FamilyUsers": "Brandon",
      "CreditBalance": "$117.00",
      "Gender": "Male"
    },
    {
      "NewName": "佳音Jia",
      "Mobile": 421169787,
      "Email": "gloria_j_tan@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "佳音jia",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Female"
    },
    {
      "NewName": "凯Kai",
      "Mobile": 421135679,
      "Email": "fgxr2583@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "凯Kai",
      "FamilyUsers": "",
      "CreditBalance": "$104.00",
      "Gender": "Male"
    },
    {
      "NewName": "双鱼王yao",
      "Mobile": 451496846,
      "Email": "wyaozu0220@163.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "双鱼王yao",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "杜和成du",
      "Mobile": 414336218,
      "Email": "chen@minchen.com.au",
      "Grade": "D",
      "GradePoints": 2,
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "杜和成",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male"
    },
    {
      "NewName": "Lin Du",
      "Mobile": 421440055,
      "Email": "dulin.du2@gmail.com",
      "Grade": "D",
      "GradePoints": 2.2,
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "杜林du",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male"
    },
    {
      "NewName": "美丽Mannie",
      "Mobile": 415518936,
      "Email": "mannieruan@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "美丽Mannie",
      "FamilyUsers": "Chris,Eric",
      "CreditBalance": "$0.00",
      "Gender": "Female"
    },
    {
      "NewName": "贝林Bei",
      "Mobile": 415098898,
      "Email": "bluesky9989@outlook.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "贝林",
      "FamilyUsers": "",
      "CreditBalance": 13,
      "Gender": "Female"
    },
    {
      "NewName": "远方Yuan",
      "Mobile": 415706307,
      "Email": "ruanfang816@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "远方",
      "FamilyUsers": "张扬zhang",
      "CreditBalance": 104,
      "Gender": "Female"
    },
    {
      "NewName": "阿布Bu",
      "Mobile": 420330886,
      "Email": "deltazhang0886@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "requireChangePassword": "TRUE",
      "OldName": "阿布bu",
      "FamilyUsers": "",
      "CreditBalance": 39,
      "Gender": "Male"
    }
  ];

  ngOnInit(): void {
    //this.onCombineDatesClick();
    this.readUserJsonFile();
  }

  onPrepopulateBookingClick() {
    //this.triggerService.prepopulateBookings();
  }

  importUser() {
    this.readUserJsonFile();
  }

  readUserJsonFile() {
    var found = this.userJson.filter(x=> x.NewName!="");
    console.log(found)
    
  }


  //Test cases
  onCombineDatesClick() {
    const example = {a: 'a'} as Test;

    example?.a  // ["first", {b:3}, false]
    let x = example.b ? 'xxx':'yyy' // undefined

    console.log('print out x: ', x);

    const lastMonday = new Date('2021-03-08');
    console.log('last monday: ', lastMonday)
    const daysfromToday = this.helperService.addDays(5);


    this.helperService.addDays(5, daysfromToday);
    this.helperService.combinDateAndTime('2021-01-01', '20:00');
    this.helperService.findNextDayOfTheWeek('friday', true, lastMonday);

    var d1 = new Date('2021-02-26T00:00:00'); 
    var d2 = new Date('2021-03-31T00:00:00'); 
    var d3 = new Date('2022-01-01T00:00:00'); 

    this.helperService.findDateRangeOfCurrentWeek(d3);

    this.helperService.findWeekdays('tue', 10);

  }

}

export class Test {
  a:string;
  b:string;
}
