import { Component, OnInit } from '@angular/core';
import { TriggersService } from "../../../services/triggers.service";
import { HelperService } from "../../../common/helper.service";
@Component({
  selector: 'app-triggers',
  templateUrl: './triggers.component.html',
  styleUrls: ['./triggers.component.scss']
})
export class TriggersComponent implements OnInit {

  constructor(private triggerService: TriggersService, private helperService: HelperService) { }

   userJson = [
    {
      "NewName": "Ada",
      "Mobile": "0413262488",
      "Email": "ada.zhu80@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Ada",
      "FamilyUsers": "Justin G,Michael G",
      "CreditBalance": "$104.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Alex Ge",
      "Mobile": "0430458688",
      "Email": "completege1@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Alex Ge",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Alex Lim",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "AlexR",
      "Mobile": "0431391842",
      "Email": "raffier.alex@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Alex Raffier",
      "FamilyUsers": "",
      "CreditBalance": "$208.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "80kg Alex Zhang",
      "Mobile": "0425432866",
      "Email": "alexlongma@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Alex Zhang",
      "FamilyUsers": "",
      "CreditBalance": "$143.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Alison",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Amanda(小粉熊）",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Andi",
      "Mobile": "0405828485",
      "Email": "andichow@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Andi",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Angel Babe",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Angela Li",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Ann",
      "FamilyUsers": "Bryan",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Anna Huang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "Anna Kan",
      "Mobile": "0424074803",
      "Email": "Ranekan@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Anna Kan",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Anuradha",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Apple Yuan",
      "Mobile": "0404131309",
      "Email": "appleyuan@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Apple",
      "FamilyUsers": "Yongzhen",
      "CreditBalance": "$221.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Audrey Chen",
      "Mobile": "0411037608",
      "Email": "audreychenyx@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Audrey",
      "FamilyUsers": "Kate Deng",
      "CreditBalance": "$26.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Bella",
      "Mobile": "0415087758",
      "Email": "apriloz@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Bella",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Ben",
      "FamilyUsers": "Jennifer",
      "CreditBalance": "$13.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Benson",
      "Mobile": "0416538984",
      "Email": "asfacas13@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Benson",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Bill",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Boon",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Brendan",
      "Mobile": "0433034006",
      "Email": "brendanlow@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Brendan",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Brook",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Bruce Chen",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Bryan",
      "Mobile": "0430858417",
      "Email": "henicoo@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Bryan Wang(双鱼王）",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Canny",
      "Mobile": "0410673878",
      "Email": "cannyclk11@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Canny",
      "FamilyUsers": "Simon,Nick,Luke",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "CC",
      "Mobile": "0410988832",
      "Email": "cecilsiu428@yahoo.com.au",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "CC",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Charissa",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Charles Wang",
      "Mobile": "0413734993",
      "Email": "cwang1110@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Charles",
      "FamilyUsers": "Zoe",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Charles Song",
      "Mobile": "0416440603",
      "Email": "13467915@student.uts.edu.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Charles Song",
      "FamilyUsers": "",
      "CreditBalance": "$143.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Chins",
      "Mobile": "0412965086",
      "Email": "chinmay.rangras@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Chins",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Chook",
      "Mobile": "0402504362",
      "Email": "kmchook@outlook.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Chook",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Christina Lee",
      "Mobile": "0415415985",
      "Email": "christina3000@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Christina Lee",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Christopher",
      "FamilyUsers": "Christopher dad",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Crystal香香",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "David Dong",
      "Mobile": "0428184056",
      "Email": "David.Iris1314@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "David Dong",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "David Fung",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "David He",
      "Mobile": "0435528870",
      "Email": "dzch961@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "David He",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "David Wang",
      "Mobile": "0436658500",
      "Email": "jiabowang05@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "David W",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "DecisionTree",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Edward D",
      "Mobile": "0403052102",
      "Email": "drd777@outlook.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Edward",
      "FamilyUsers": "Christopher",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Elaine Ho",
      "Mobile": "0452612565",
      "Email": "oikhei@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Elaine Ho",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Elly赵欣",
      "Mobile": "0408642329",
      "Email": "ecnu_2000@163.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Elly赵欣",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Eric Han",
      "FamilyUsers": "",
      "CreditBalance": "$13.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "Ethan Jin",
      "Mobile": "0468512080",
      "Email": "yingwu.jin@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Ethan电工",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "eugenia Lee",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Fan Jiang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Feng",
      "Mobile": "0401599736",
      "Email": "marco_yufeng@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Feng",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Fiona",
      "FamilyUsers": "Victor,亮亮",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Francis",
      "Mobile": "0434087284",
      "Email": "francishe2007@yahoo.com.au",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Francis",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Frank",
      "Mobile": "0402155868",
      "Email": "frankyangtao@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Frank",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Frank Z",
      "Mobile": "0415615698",
      "Email": "changle2012@yahoo.com.au",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Frank Zhang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Gary",
      "Mobile": "0478151916",
      "Email": "gychang2000@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Gary",
      "FamilyUsers": "Enoch",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Glen",
      "Mobile": "0406436861",
      "Email": "wangxiao_ch@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Glen",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Hannah",
      "Mobile": "0403649446",
      "Email": "ka_zling@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Hannah",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Hardeep",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Henry Su",
      "Mobile": "0423523823",
      "Email": "henrysuplus@yahoo.com.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Henry",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Herbert",
      "Mobile": "0420572215",
      "Email": "herbertyuan22@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Herbert",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Hugh",
      "Mobile": "0451668958",
      "Email": "huhe1969@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Hugh",
      "FamilyUsers": "Renee",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Cream",
      "Mobile": "0431695247",
      "Email": "happyjane_crying@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Iris",
      "FamilyUsers": "Neil,Sean",
      "CreditBalance": "$104.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jack Wang",
      "FamilyUsers": "Lin",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Jack L",
      "Mobile": "0404139888",
      "Email": "nice_jack@live.cn",
      "Grade": "F",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jack(Helen)",
      "FamilyUsers": "Helen,Elma",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "JackyZ",
      "Mobile": "0410138150",
      "Email": "jacky.zhang.au@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jacky Zhang",
      "FamilyUsers": "Megan,Bei,Evan",
      "CreditBalance": "$260.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jacob",
      "FamilyUsers": "Callum",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jacob-Milk",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jade",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "James Chen",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jarvis",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jasmine",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Jason Chin",
      "Mobile": "0405536604",
      "Email": "jasonchchin@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jason Chin",
      "FamilyUsers": "Kate",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jason Cui",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jason刘",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jay(Indian)",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Jeff Wang",
      "Mobile": "0417009871",
      "Email": "wenoch@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jeff",
      "FamilyUsers": "Maggie,Maggie Yao",
      "CreditBalance": "$104.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jeff Shen",
      "FamilyUsers": "PeiPei,FeiFei",
      "CreditBalance": "$180.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Jency",
      "Mobile": "0438680029",
      "Email": "adepttravels@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jency",
      "FamilyUsers": "Jason",
      "CreditBalance": "$26.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Jennifer Xu",
      "Mobile": "0414360152",
      "Email": "jenniferwen00@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jennifer",
      "FamilyUsers": "Kid,Pengfei",
      "CreditBalance": "$26.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jenny",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jeremy",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jerry",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jerry Yam",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "JessicaW",
      "Mobile": "0452581109",
      "Email": "wang_j1122@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jessica W",
      "FamilyUsers": "Jason Z",
      "CreditBalance": "$39.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jessica Z",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Jim L",
      "Mobile": "0466475033",
      "Email": "topliu88@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Jim L",
      "FamilyUsers": "Shirley Y",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Joanne",
      "FamilyUsers": "Joe",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Jocelyn",
      "Mobile": "0433848970",
      "Email": "leunglksm@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Joceyln",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "John",
      "FamilyUsers": "Annie",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jon",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Josh Zhang",
      "Mobile": "0433330987",
      "Email": "joshzhangjobs@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Josh",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Josh T",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Jun",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "JZ",
      "Mobile": "0409979198",
      "Email": "jackeal_zhuj@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "JZ",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Kai",
      "Mobile": "0402822228",
      "Email": "kaisquared90@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Kai",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Karthik",
      "Mobile": "0469241444",
      "Email": "r.karthik@yahoo.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Karthik",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Kathy",
      "Mobile": "0414266070",
      "Email": "Kathy0721@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Kathy",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "KevinW",
      "Mobile": "0433499901",
      "Email": "kevin.wangwei@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Kevin Wang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Lance",
      "Mobile": "0423432057",
      "Email": "truehoho@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Lance",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Lenise",
      "Mobile": "0469915138",
      "Email": "lenise_yeoh@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Lenise",
      "FamilyUsers": "Jet,Say",
      "CreditBalance": "$130.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Leon",
      "Mobile": "0433671656",
      "Email": "leonlai1997@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Leon",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "LilyC",
      "FamilyUsers": "Angus M",
      "CreditBalance": "$30.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "Lionel",
      "Mobile": "0423080826",
      "Email": "lionelong@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Lionel",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Lisa",
      "FamilyUsers": "Gary,Kevin",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Long",
      "Mobile": "0401021568",
      "Email": "h_lx@hotmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Long",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Lorrence",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Luc",
      "Mobile": "0413780136",
      "Email": "bei2004@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Luc",
      "FamilyUsers": "Sydney,Kate",
      "CreditBalance": "$130.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Mae",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Magesh",
      "Mobile": "0424611007",
      "Email": "rymagesh@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Magesh",
      "FamilyUsers": "",
      "CreditBalance": "$104.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Maggie梅",
      "FamilyUsers": "Maggie2,Grace",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Maggie 瀚文",
      "Mobile": "0468488368",
      "Email": "mzhangau@outlook.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Maggie瀚文书院",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Manju",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Manny",
      "Mobile": "0406726588",
      "Email": "manny.gongz@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Manny",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Marcus",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Maria",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Mark Chen",
      "Mobile": "0466556068",
      "Email": "mloves.chen@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Mark Chen",
      "FamilyUsers": "",
      "CreditBalance": 0,
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Martin马腾",
      "FamilyUsers": "TIAN",
      "CreditBalance": "$20.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "mashiry",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Matt",
      "Mobile": "0439116666",
      "Email": "mattshi81@hotmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Matt",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Michael",
      "Mobile": "0425033441",
      "Email": "845524343@qq.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Michael",
      "FamilyUsers": "Melody",
      "CreditBalance": "$13.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Michael M",
      "FamilyUsers": "",
      "CreditBalance": "$13.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Michael Xu",
      "Mobile": "0411652088",
      "Email": "michael202125@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Michael Xu",
      "FamilyUsers": "Sarah",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Michael Zhang",
      "Mobile": "0421437705",
      "Email": "mzhang668@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Michael Z",
      "FamilyUsers": "Melody",
      "CreditBalance": "$117.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Michelle",
      "FamilyUsers": "Bruce",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Nancy",
      "FamilyUsers": "Frank Wu,Sean Wu,Ryan Wu",
      "CreditBalance": "$10.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Nicole D",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Owen",
      "Mobile": "0420518070",
      "Email": "zquake@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Owen",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "PatrickH",
      "Mobile": "0432125002",
      "Email": "patrickhu26358787@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Patrick Hu",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Paulo",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Peggy",
      "Mobile": "0479159678",
      "Email": "peggy.ling.au@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Peggy",
      "FamilyUsers": "Rylan,Lincoln,Mason",
      "CreditBalance": "$26.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Peter wang",
      "Mobile": "0433007578",
      "Email": "qiudongw@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Peter Wang",
      "FamilyUsers": "Jensen,Eva Wang",
      "CreditBalance": "$13.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Phoebe",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Poh",
      "Mobile": "0413228977",
      "Email": "bukit_chong@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "POH",
      "FamilyUsers": "",
      "CreditBalance": "$65.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "hipolly",
      "Mobile": "0415885188",
      "Email": "topollykwok@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Polly",
      "FamilyUsers": "Andrew",
      "CreditBalance": "$52.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Prakash",
      "Mobile": "0404371773",
      "Email": "Prakash.varu@yahoo.com.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Prakash",
      "FamilyUsers": "",
      "CreditBalance": "$13.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Raj",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Robert-Bee",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "RobinZhang",
      "Mobile": "0407803979",
      "Email": "cs.zhanghong@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Robin-Lazycat",
      "FamilyUsers": "Ryan",
      "CreditBalance": "$130.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Rozana",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Sammy",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Samuel",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Satira",
      "FamilyUsers": "Segar",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "ScottZ",
      "Mobile": "0406368287",
      "Email": "scott.z.zhuo@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Scott Zuo",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Shekhar",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Shirey",
      "FamilyUsers": "Rick",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Shirley ACE",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Shirley",
      "Mobile": "0410638127",
      "Email": "shiroly@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Shirley(Eric)",
      "FamilyUsers": "Angus,Marus,Venus",
      "CreditBalance": "$20.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "SimonT",
      "Mobile": "0421132308",
      "Email": "simonpt2000@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Simon T",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "F",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Stanley",
      "FamilyUsers": "Sara",
      "CreditBalance": "$30.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Stella",
      "FamilyUsers": "Jacky,Selina",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "Steven Liu",
      "Mobile": "0402505299",
      "Email": "2339297951@qq.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Steven Liu",
      "FamilyUsers": "",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Tammy",
      "Mobile": "0431662310",
      "Email": "au.tammy@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Tammy",
      "FamilyUsers": "",
      "CreditBalance": "$117.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Terry",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": "Yes"
    },
    {
      "NewName": "Thomas",
      "Mobile": "0422945805",
      "Email": "thomastsang7388@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Thomas",
      "FamilyUsers": "Iris T",
      "CreditBalance": "$260.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Ting CA",
      "Mobile": "0415226713",
      "Email": "ququ1102@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Ting",
      "FamilyUsers": "Rain",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Tom",
      "Mobile": "0418215888",
      "Email": "shihuaichen@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Tom",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Tommy",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Tony C",
      "Mobile": "0430511668",
      "Email": "tony.cao77@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Tony C",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Van",
      "FamilyUsers": "Mel",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Veige",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Vincent",
      "Mobile": "0427392166",
      "Email": "vshc1@yahoo.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Vincent",
      "FamilyUsers": "Enoch",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Visitor",
      "Mobile": "0000000000",
      "Email": "visitor@gmail.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Visitor1",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "visitor2",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "visitor3",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Vivi",
      "FamilyUsers": "Charles Vivi",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Vivian",
      "FamilyUsers": "Lly阿良,Mathew",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Warren",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "Wei",
      "Mobile": "0449984324",
      "Email": "wei_lu@live.com.au",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Wei",
      "FamilyUsers": "",
      "CreditBalance": 0,
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Wendy Yang",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "William",
      "FamilyUsers": "Amanda,Xiayan",
      "CreditBalance": "$39.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Wilson",
      "FamilyUsers": "Annie",
      "CreditBalance": "$91.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Wing",
      "Mobile": "0424125197",
      "Email": "wingyang502@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Wing",
      "FamilyUsers": "",
      "CreditBalance": "$78.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Xiao",
      "Mobile": "0434130413",
      "Email": "mailtohx@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Xiao",
      "FamilyUsers": "Mindy,Qiandai,Villy",
      "CreditBalance": "$65.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Yang",
      "Mobile": "0424907646",
      "Email": "yyl901015@126.com",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "Yang",
      "FamilyUsers": "Claire",
      "CreditBalance": "$20.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "Zaka",
      "Mobile": "0433396668",
      "Email": "zaka.lei@gmail.com",
      "Grade": "A",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "Zakka",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "何平He",
      "Mobile": "0420779229",
      "Email": "1171750071@qq.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "何平",
      "FamilyUsers": "Brandon",
      "CreditBalance": "$117.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "佳音Jia",
      "Mobile": "0421169787",
      "Email": "gloria_j_tan@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "佳音jia",
      "FamilyUsers": "",
      "CreditBalance": "$91.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "凯Kai",
      "Mobile": "0421135679",
      "Email": "fgxr2583@gmail.com",
      "Grade": "C",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "凯Kai",
      "FamilyUsers": "",
      "CreditBalance": "$104.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "南十字星nan",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "双鱼王yao",
      "Mobile": "0451496846",
      "Email": "wyaozu0220@163.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "双鱼王yao",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": "Yes"
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "啊Jun",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "娟娟",
      "FamilyUsers": "Roy",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "日月星Shanow",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "星星xin",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "杜和成du",
      "Mobile": "0414336218",
      "Email": "chen@minchen.com.au",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "杜和成",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "Lin Du",
      "Mobile": "0421440055",
      "Email": "dulin.du2@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "杜林du",
      "FamilyUsers": "",
      "CreditBalance": "$26.00",
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "梅mei",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "正泰Dylan",
      "FamilyUsers": "",
      "CreditBalance": "$52.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "王冰Bing",
      "FamilyUsers": "",
      "CreditBalance": "$0.00",
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "美丽Mannie",
      "Mobile": "0415518936",
      "Email": "mannieruan@hotmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "美丽Mannie",
      "FamilyUsers": "Chris,Eric",
      "CreditBalance": "$0.00",
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "贝林Bei",
      "Mobile": "0415098898",
      "Email": "bluesky9989@outlook.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "贝林",
      "FamilyUsers": "",
      "CreditBalance": 13,
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "远方Yuan",
      "Mobile": "0415706307",
      "Email": "ruanfang816@gmail.com",
      "Grade": "D",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "远方",
      "FamilyUsers": "张扬zhang",
      "CreditBalance": 104,
      "Gender": "Female",
      "Required": "",
      "Overrides": ""
    },
    {
      "NewName": "",
      "Mobile": "",
      "Email": "",
      "Grade": "",
      "GradePoints": "",
      "IsCreditUser": "",
      "OldName": "钞元yuan",
      "FamilyUsers": "",
      "CreditBalance": 0,
      "Gender": "Male",
      "Required": "FALSE",
      "Overrides": ""
    },
    {
      "NewName": "阿布Bu",
      "Mobile": "0420330886",
      "Email": "deltazhang0886@gmail.com",
      "Grade": "E",
      "GradePoints": "",
      "IsCreditUser": "TRUE",
      "OldName": "阿布bu",
      "FamilyUsers": "",
      "CreditBalance": 39,
      "Gender": "Male",
      "Required": "",
      "Overrides": ""
    }
  ];

  ngOnInit(): void {
    //this.onCombineDatesClick();
    this.readUserJsonFile();
  }

  onPrepopulateBookingClick() {
    //this.triggerService.prepopulateBookings();
  }

  readUserJsonFile() {
    var found = this.userJson.filter(x=>x.Required=="" && x.NewName!="");
    console.log(found)
    
  }


  //Test cases
  onCombineDatesClick() {
    const example = {a: 'a'} as Test;

    example?.a  // ["first", {b:3}, false]
    let x = example.b ? 'xxx':'yyy' // undefined

    console.log('print out x: ', x);

    const lastMonday = new Date('2021-03-08');
    console.log('last monday: ', lastMonday)
    const daysfromToday = this.helperService.addDays(5);


    this.helperService.addDays(5, daysfromToday);
    this.helperService.combinDateAndTime('2021-01-01', '20:00');
    this.helperService.findNextDayOfTheWeek('friday', true, lastMonday);

    var d1 = new Date('2021-02-26T00:00:00'); 
    var d2 = new Date('2021-03-31T00:00:00'); 
    var d3 = new Date('2022-01-01T00:00:00'); 

    this.helperService.findDateRangeOfCurrentWeek(d3);

    this.helperService.findWeekdays('tue', 10);

  }

}

export class Test {
  a:string;
  b:string;
}
