name: UAT - HBC deploy
'on':
  push:
    branches:
        - 'feature/**'
        - 'features/**'
      
jobs:
  uat_build_deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
            node-version: '18.13.0'
      - run: sudo apt-get update
      - run: sudo apt-get upgrade openssl      
      - run: npm install
      - name: create env file
        run: |
          touch .env
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env
          echo MAIL_URL=${{ secrets.MAIL_URL }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
          echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
          echo STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} >> .env
          echo MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} >> .env
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }} >> .env  
      - run: npm run config
      - run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HBC666_UAT }}'
          channelId: live
          projectId: hbc-uat-9f2ad
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          NODE_OPTIONS: --openssl-legacy-provider
