name: Deploying UAT
'on':
  push:
    branches:
      - developer
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g @angular/cli
      - name: create env file
        run: |
          touch .env
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env
          echo MAIL_URL=${{ secrets.MAIL_URL }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
      - run: npm run config && ng build --dev --output-path=public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HBC666_UAT }}'
          channelId: live
          projectId: hbc-uat-9f2ad
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels