name: Deployng Prod
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm install -g @angular/cli
      - name: create env file
        run: |
          touch .env
          echo PRODUCTION=${{ secrets.PRODUCTION }} >> .env
          echo MAIL_URL=${{ secrets.MAIL_URL }} >> .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }} >> .env
          echo PROJECT_ID=${{ secrets.PROJECT_ID }} >> .env
          echo STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }} >> .env
          echo MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }} >> .env
          echo APP_ID=${{ secrets.APP_ID }} >> .env
          echo MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }} >> .env  
      - run: npm run config          
      - run: ng build --prod --progress --output-path=public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_HBC666 }}'
          channelId: live
          projectId: hbclub-919aa
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
          PRODUCTION: '${{ secrets.PRODUCTION }}'
          MAIL_URL: '${{ secrets.MAIL_URL }}'
          API_KEY: '${{ secrets.API_KEY }}'
